"""empty message

Revision ID: 10d76bfd3a33
Revises: 
Create Date: 2026-07-10 18:41:48.165349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d76bfd3a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_working_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_profile_id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_datetime', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('appointment_datetime')

    op.drop_table('business_working_schedule')
    # ### end Alembic commands ###
