"""Create business working schedule table

Revision ID: 96bae65aff89
Revises: e97243058685
Create Date: 2026-07-04 00:09:00.225037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bae65aff89'
down_revision = 'e97243058685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_working_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.String(length=5), nullable=False),
    sa.Column('closing_time', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_working_schedule')
    # ### end Alembic commands ###
