"""empty message

Revision ID: b4bfbbbc65c0
Revises: e8e8f1454eab
Create Date: 2026-06-24 19:04:33.546012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bfbbbc65c0'
down_revision = 'e8e8f1454eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_slug_key'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('category_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
