"""empty message

Revision ID: d971aa8dab6c
Revises: b4bfbbbc65c0
Create Date: 2026-06-28 19:19:13.043361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd971aa8dab6c'
down_revision = 'b4bfbbbc65c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_datetime', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('appointment_datetime')

    # ### end Alembic commands ###
