"""Refactor user and add client and business profiles

Revision ID: f8ce1f99a5b8
Revises: 3ffdab51b888
Create Date: 2026-06-14 17:52:39.281652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ce1f99a5b8'
down_revision = '3ffdab51b888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('business_name', sa.String(
                        length=120), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('category', sa.String(
                        length=80), nullable=False),
                    sa.Column('country', sa.String(length=80), nullable=False),
                    sa.Column('province', sa.String(
                        length=80), nullable=False),
                    sa.Column('city', sa.String(length=80), nullable=False),
                    sa.Column('postal_code', sa.String(
                        length=20), nullable=False),
                    sa.Column('address', sa.String(
                        length=180), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('client_profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(
            length=20), nullable=False, server_default='client'))
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(
            length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(
            length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('role')

    op.drop_table('client_profile')
    op.drop_table('business_profile')
    # ### end Alembic commands ###
