"""empty message

Revision ID: fcd9674e9729
Revises: 5e354d5d3cef
Create Date: 2026-06-17 00:17:00.701341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd9674e9729'
down_revision = '5e354d5d3cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_profile_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_portfolio')
    op.drop_table('business_gallery')
    # ### end Alembic commands ###
